version: '3.8'

services:
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql

volumes:
  mysql_data:
